GS_BaseUrl: "http://rinchen-dos.cnb.csic.es/"
GS_EnsemblServer: "http://rest.ensembl.org/"
GS_UniServer: "http://www.uniprot.org/"
GS_SIFTSUrl: "http://ftp.ebi.ac.uk/pub/databases/msd/sifts/xml/"
GS_PDBeServer: "https://www.ebi.ac.uk/pdbe/api/"
GS_InterproURL: "http://www.ebi.ac.uk/interpro/protein/"
GS_DsysmapURL: "https://dsysmap.irbbarcelona.org/api/getMutationsForProteins?protein_ids="
GS_Interactome3Dpdb: "https://interactome3d.irbbarcelona.org/api/getPdbFile?"
GS_Interactome3D: "https://interactome3d.irbbarcelona.org/network.php?connect=true&rs=true"
GS_MobiURL: "http://mobidb.bio.unipd.it/ws/"
GS_PfamURL: "http://pfam.xfam.org/"
GS_SmartURL: "http://smart.embl.de/smart/batch.pl?TEXTONLY=1&INCLUDE_SIGNALP=1&IDS="
GS_UniProtServer: "https://www.ebi.ac.uk/proteins/api"
GS_PDB_REDO: "http://pdb-redo.eu/db/"
GS_ISOLDE: "ws/lrs/files/modifiedPdb/isolde/"
GS_REFMAC: "ws/lrs/files/modifiedPdb/refmac/"
GS_SWISSMODEL: "https://swissmodel.expasy.org/interactive/"
GS_ALPHAFOLD: "/ws/lrs/files/computModels/AlphaFold/"
GS_BSM_ARC: "https://bsma.pdbj.org/rest/public/projects/download/15/"
GS_EMDB: "ftp://ftp.ebi.ac.uk/pub/databases/emdb/structures/"
GS_PDBe: "https://www.ebi.ac.uk/pdbe/entry-files/download/"

GS_LocalApp: "/services/bionotes/apps/bionotes/"
GS_LocalData: "/services/bionotes/apps/bionotes/data/"
GS_LocalAppDB: "/services/bionotes/apps/bionotes/db/"
GS_LocalUpload: "/services/bionotes/apps/bionotes/public/upload/"
GS_LocalSeq: "/services/bionotes/apps/bionotes/data/tmp_seq/"
GS_LocalSIFTS: "/services/bionotes/databases/SIFTS/XML/"
GS_LocalScripts: "/services/bionotes/apps/bionotes/scripts/"
GS_LocalMolProobity_tmp: "/services/bionotes/apps/bionotes/data/tmp_mp/"
GS_LocalDB: "/services/bionotes/databases/"
GS_LocalInteractome3D: "/services/bionotes/apps/bionotes/data/interactome3d/"
GS_LocalContingencyPDB: "/compute/contingency/pdb/"
GS_LocalContingencyACC: "/compute/contingency/uniprot/"

GS_IdentityMatrixFile: "/services/bionotes/apps/ENSEMBL/IDENTITY"  
GS_ElmScript: "/services/bionotes/apps/ELMDB/get_elm_data"

